/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package controlcalidad;
import de.javasoft.plaf.synthetica.SyntheticaBlackMoonLookAndFeel;
import java.awt.Frame;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import javax.swing.JButton;
import javax.swing.UIManager;
import javax.swing.JOptionPane;
/**
 *
 * @author dampyre
 */
public class Base extends javax.swing.JFrame {

    /**
     * Creates new form Base
     */
    private boolean estaFull = false;
    private boolean LoginFull = true;
    static GraphicsDevice grafica=
                GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
   
    public Base() {
        initComponents();
        ConfiguracionVentana();
        Login();
        
    }
    public void Login(){
           VentanaFrmPrincipal vi = new VentanaFrmPrincipal();
        vi.setResizable(false);
        vi.setMaximizable(true);
        vi.setIconifiable(true);
        vi.setClosable(true);
        vi.setVisible(true);/*se le asigna este metodo para hacerlo visible obvio*/
       
        
        panelInterno.add(vi);
        
    }
    public void ConfiguracionVentana(){
        this.setSize(800,600);
        this.setExtendedState(Base.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInterno = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuAbrir = new javax.swing.JMenu();
        abrir = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuSalir = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuCtrlOT = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(panelInterno, java.awt.BorderLayout.CENTER);

        MenuAbrir.setText("Archivo");

        abrir.setText("Abrir");
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });
        MenuAbrir.add(abrir);

        jMenuItem2.setText("Cerrar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MenuAbrir.add(jMenuItem2);
        MenuAbrir.add(jSeparator1);

        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        MenuAbrir.add(menuSalir);

        jMenuBar1.add(MenuAbrir);

        jMenu1.setText("Otros");

        jMenuItem1.setText("FullScreen");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        menuCtrlOT.setText("Control OT");
        menuCtrlOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCtrlOTActionPerformed(evt);
            }
        });
        jMenu1.add(menuCtrlOT);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
        // TODO add your handling code here:
        VentanaFrmPrincipal vi = new VentanaFrmPrincipal();
        //vi.setResizable(true);
        vi.setMaximizable(true);
        vi.setIconifiable(true);
        vi.setClosable(true);
        vi.setVisible(true);/*se le asigna este metodo para hacerlo visible obvio*/
        
        panelInterno.add(vi);
        
    }//GEN-LAST:event_abrirActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuSalirActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         if(!estaFull)
                        grafica.setFullScreenWindow(this);
                else
                        grafica.setFullScreenWindow(null);
                estaFull = !estaFull;
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuCtrlOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCtrlOTActionPerformed
        // TODO add your handling code here:
          ControlOT OT = new ControlOT();
        OT.setResizable(true);
        OT.setMaximizable(true);
        OT.setIconifiable(true);
        OT.setClosable(true);
        OT.setVisible(true);/*se le asigna este metodo para hacerlo visible obvio*/
        
        panelInterno.add(OT);
    }//GEN-LAST:event_menuCtrlOTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
      try{
            UIManager.setLookAndFeel(new SyntheticaBlackMoonLookAndFeel());
        }catch(Exception ex)
        {
         JOptionPane.showMessageDialog(null,"error al cargar el estilo","error"+ ex.getMessage(),JOptionPane.ERROR_MESSAGE);   
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Base().setVisible(true);
               
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAbrir;
    private javax.swing.JMenuItem abrir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menuCtrlOT;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JDesktopPane panelInterno;
    // End of variables declaration//GEN-END:variables
}
