/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package controlcalidad;
import java.io.*;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author dampyre
 */
public class VentanaFrmPrincipal extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaFrmPrincipal
     */
    String usuario,password;
    
    public VentanaFrmPrincipal() {
        initComponents();
        
        
    }
    
    boolean validarUsuario (String usr, String pass) throws IOException {
        try{
            Class.forName("org.gjt.mm.mysql.Driver");
            Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/login","root", "s0lang3");
            Statement instruccion = conexion.createStatement();
            ResultSet resultadoConsulta = instruccion.executeQuery("SELECT * FROM usuarios WHERE usuario ='"+usr+"'AND password='"+pass+"'");
                if(resultadoConsulta.first())
                    return true ;//el usuario es valido 
                
                else
                    return false; //el usuario no existe
        }catch(Exception e){
          JOptionPane.showMessageDialog(null,"no se puede conectar a la base de datos","error"+ e.getMessage(),JOptionPane.ERROR_MESSAGE);
          return false;
        }
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();

        jLabel1.setText("Usuario");

        jLabel2.setText("Pasword");

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(btnIngresar)))
                .addContainerGap(304, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(btnIngresar)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        try{
            //validacion de usuario
            if(txtUsuario.getText().length()>0 && txtPassword.getText().length()>0){
                
                if(validarUsuario(txtUsuario.getText(),txtPassword.getText())){
                    ControlOT OT = new ControlOT();
                    OT.setResizable(true);
                    OT.setMaximizable(true);
                    OT.setIconifiable(true);
                    OT.setClosable(true);
                    OT.setVisible(true);
                    
                    setVisible(false);
                }else{
                    JOptionPane.showMessageDialog(null,"El nombre de usuario o contraseña no son validos");
                    txtUsuario.setText("");
                    txtPassword.setText("");
                    txtUsuario.requestFocusInWindow();
                }
            }else{
                JOptionPane.showMessageDialog(null, "no debe dejar ningun campo en blanco ");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
